name: URL Checker (PR)

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: URL Link Check
        uses: Diolor/github-action-markdown-link-check@1.3
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/config/url-checker-config.json'
          check-modified-files-only: 'yes'
